<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ExportedRolPermisoSeeder extends Seeder
{
    public function run()
    {
        DB::beginTransaction();
        DB::statement('SET session_replication_role = replica;'); // for postgres to disable FK checks

        DB::table('rol_permiso')->truncate();

        DB::table('rol_permiso')->insert([
            array (
  'id' => 1,
  'rol_id' => 1,
  'permiso_id' => 1,
  'created_at' => NULL,
  'updated_at' => NULL,
),
        array (
  'id' => 2,
  'rol_id' => 1,
  'permiso_id' => 2,
  'created_at' => NULL,
  'updated_at' => NULL,
),
        array (
  'id' => 3,
  'rol_id' => 1,
  'permiso_id' => 3,
  'created_at' => NULL,
  'updated_at' => NULL,
),
        array (
  'id' => 4,
  'rol_id' => 1,
  'permiso_id' => 4,
  'created_at' => NULL,
  'updated_at' => NULL,
),
        array (
  'id' => 5,
  'rol_id' => 1,
  'permiso_id' => 5,
  'created_at' => NULL,
  'updated_at' => NULL,
),
        array (
  'id' => 6,
  'rol_id' => 1,
  'permiso_id' => 6,
  'created_at' => NULL,
  'updated_at' => NULL,
),
        array (
  'id' => 7,
  'rol_id' => 1,
  'permiso_id' => 7,
  'created_at' => NULL,
  'updated_at' => NULL,
),
        array (
  'id' => 8,
  'rol_id' => 1,
  'permiso_id' => 8,
  'created_at' => NULL,
  'updated_at' => NULL,
),
        array (
  'id' => 9,
  'rol_id' => 1,
  'permiso_id' => 9,
  'created_at' => NULL,
  'updated_at' => NULL,
),
        array (
  'id' => 10,
  'rol_id' => 1,
  'permiso_id' => 10,
  'created_at' => NULL,
  'updated_at' => NULL,
),
        array (
  'id' => 11,
  'rol_id' => 1,
  'permiso_id' => 11,
  'created_at' => NULL,
  'updated_at' => NULL,
),
        array (
  'id' => 12,
  'rol_id' => 1,
  'permiso_id' => 12,
  'created_at' => NULL,
  'updated_at' => NULL,
),
        array (
  'id' => 13,
  'rol_id' => 1,
  'permiso_id' => 13,
  'created_at' => NULL,
  'updated_at' => NULL,
),
        array (
  'id' => 14,
  'rol_id' => 1,
  'permiso_id' => 14,
  'created_at' => NULL,
  'updated_at' => NULL,
),
        array (
  'id' => 15,
  'rol_id' => 1,
  'permiso_id' => 15,
  'created_at' => NULL,
  'updated_at' => NULL,
),
        array (
  'id' => 16,
  'rol_id' => 1,
  'permiso_id' => 16,
  'created_at' => NULL,
  'updated_at' => NULL,
),
        array (
  'id' => 17,
  'rol_id' => 1,
  'permiso_id' => 17,
  'created_at' => NULL,
  'updated_at' => NULL,
),
        array (
  'id' => 18,
  'rol_id' => 1,
  'permiso_id' => 18,
  'created_at' => NULL,
  'updated_at' => NULL,
),
        array (
  'id' => 19,
  'rol_id' => 1,
  'permiso_id' => 19,
  'created_at' => NULL,
  'updated_at' => NULL,
),
        array (
  'id' => 20,
  'rol_id' => 1,
  'permiso_id' => 20,
  'created_at' => NULL,
  'updated_at' => NULL,
),
        array (
  'id' => 21,
  'rol_id' => 1,
  'permiso_id' => 21,
  'created_at' => NULL,
  'updated_at' => NULL,
),
        array (
  'id' => 22,
  'rol_id' => 1,
  'permiso_id' => 22,
  'created_at' => NULL,
  'updated_at' => NULL,
),
        array (
  'id' => 23,
  'rol_id' => 1,
  'permiso_id' => 23,
  'created_at' => NULL,
  'updated_at' => NULL,
),
        array (
  'id' => 24,
  'rol_id' => 1,
  'permiso_id' => 24,
  'created_at' => NULL,
  'updated_at' => NULL,
),
        array (
  'id' => 25,
  'rol_id' => 1,
  'permiso_id' => 25,
  'created_at' => NULL,
  'updated_at' => NULL,
),
        array (
  'id' => 26,
  'rol_id' => 1,
  'permiso_id' => 26,
  'created_at' => NULL,
  'updated_at' => NULL,
),
        array (
  'id' => 27,
  'rol_id' => 1,
  'permiso_id' => 27,
  'created_at' => NULL,
  'updated_at' => NULL,
),
        array (
  'id' => 28,
  'rol_id' => 1,
  'permiso_id' => 28,
  'created_at' => NULL,
  'updated_at' => NULL,
),
        array (
  'id' => 29,
  'rol_id' => 1,
  'permiso_id' => 29,
  'created_at' => NULL,
  'updated_at' => NULL,
),
        array (
  'id' => 30,
  'rol_id' => 1,
  'permiso_id' => 30,
  'created_at' => NULL,
  'updated_at' => NULL,
),
        array (
  'id' => 31,
  'rol_id' => 1,
  'permiso_id' => 31,
  'created_at' => NULL,
  'updated_at' => NULL,
),
        array (
  'id' => 32,
  'rol_id' => 1,
  'permiso_id' => 32,
  'created_at' => NULL,
  'updated_at' => NULL,
),
        array (
  'id' => 33,
  'rol_id' => 1,
  'permiso_id' => 33,
  'created_at' => NULL,
  'updated_at' => NULL,
),
        array (
  'id' => 34,
  'rol_id' => 2,
  'permiso_id' => 18,
  'created_at' => NULL,
  'updated_at' => NULL,
),
        array (
  'id' => 35,
  'rol_id' => 2,
  'permiso_id' => 27,
  'created_at' => NULL,
  'updated_at' => NULL,
),
        array (
  'id' => 36,
  'rol_id' => 2,
  'permiso_id' => 29,
  'created_at' => NULL,
  'updated_at' => NULL,
),
        array (
  'id' => 37,
  'rol_id' => 2,
  'permiso_id' => 31,
  'created_at' => NULL,
  'updated_at' => NULL,
),
        array (
  'id' => 38,
  'rol_id' => 2,
  'permiso_id' => 32,
  'created_at' => NULL,
  'updated_at' => NULL,
),
        array (
  'id' => 39,
  'rol_id' => 2,
  'permiso_id' => 33,
  'created_at' => NULL,
  'updated_at' => NULL,
),
        array (
  'id' => 40,
  'rol_id' => 3,
  'permiso_id' => 11,
  'created_at' => NULL,
  'updated_at' => NULL,
),
        array (
  'id' => 41,
  'rol_id' => 3,
  'permiso_id' => 12,
  'created_at' => NULL,
  'updated_at' => NULL,
),
        array (
  'id' => 42,
  'rol_id' => 3,
  'permiso_id' => 14,
  'created_at' => NULL,
  'updated_at' => NULL,
),
        array (
  'id' => 43,
  'rol_id' => 3,
  'permiso_id' => 15,
  'created_at' => NULL,
  'updated_at' => NULL,
),
        array (
  'id' => 44,
  'rol_id' => 3,
  'permiso_id' => 16,
  'created_at' => NULL,
  'updated_at' => NULL,
),
        array (
  'id' => 45,
  'rol_id' => 3,
  'permiso_id' => 17,
  'created_at' => NULL,
  'updated_at' => NULL,
),
        array (
  'id' => 46,
  'rol_id' => 3,
  'permiso_id' => 18,
  'created_at' => NULL,
  'updated_at' => NULL,
),
        array (
  'id' => 47,
  'rol_id' => 3,
  'permiso_id' => 19,
  'created_at' => NULL,
  'updated_at' => NULL,
),
        array (
  'id' => 48,
  'rol_id' => 3,
  'permiso_id' => 20,
  'created_at' => NULL,
  'updated_at' => NULL,
),
        array (
  'id' => 49,
  'rol_id' => 3,
  'permiso_id' => 22,
  'created_at' => NULL,
  'updated_at' => NULL,
),
        array (
  'id' => 50,
  'rol_id' => 3,
  'permiso_id' => 23,
  'created_at' => NULL,
  'updated_at' => NULL,
),
        array (
  'id' => 51,
  'rol_id' => 3,
  'permiso_id' => 24,
  'created_at' => NULL,
  'updated_at' => NULL,
),
        array (
  'id' => 52,
  'rol_id' => 3,
  'permiso_id' => 25,
  'created_at' => NULL,
  'updated_at' => NULL,
),
        array (
  'id' => 53,
  'rol_id' => 3,
  'permiso_id' => 26,
  'created_at' => NULL,
  'updated_at' => NULL,
),
        array (
  'id' => 54,
  'rol_id' => 3,
  'permiso_id' => 29,
  'created_at' => NULL,
  'updated_at' => NULL,
),
        array (
  'id' => 55,
  'rol_id' => 3,
  'permiso_id' => 31,
  'created_at' => NULL,
  'updated_at' => NULL,
),
        array (
  'id' => 56,
  'rol_id' => 3,
  'permiso_id' => 32,
  'created_at' => NULL,
  'updated_at' => NULL,
),
        array (
  'id' => 57,
  'rol_id' => 3,
  'permiso_id' => 33,
  'created_at' => NULL,
  'updated_at' => NULL,
)
        ]);

        DB::statement('SET session_replication_role = default;');
        DB::commit();
    }
}